# Generated by Django 4.2.11 on 2024-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_tripcomment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripcomment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
