# Generated by Django 4.2.11 on 2024-03-14 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travellerprofile', '0002_alter_traveller_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('itinerary', models.TextField(max_length=1000)),
                ('region', models.IntegerField(choices=[(0, 'UK'), (1, 'Europe'), (2, 'Asia'), (3, 'Oceania'), (4, 'North America'), (5, 'South America'), (6, 'Africa'), (7, 'Middle East')], default=0)),
                ('accomm_type', models.IntegerField(blank=True, choices=[(0, 'Tent'), (1, 'Caravan'), (2, 'Camper Van'), (3, 'Hotel/Booked Room')])),
                ('interests', models.CharField(blank=True, max_length=150)),
                ('startDate', models.DateField(blank=True)),
                ('endDate', models.DateField(blank=True)),
                ('trip_photo', models.ImageField(blank=True, default='placeholder', upload_to='tripImages/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_planned', to='travellerprofile.traveller')),
            ],
        ),
    ]
