# Generated by Django 4.2.11 on 2024-03-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travellerprofile', '0002_alter_traveller_profile_photo'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField(max_length=1000)),
                ('trip_photo', models.ImageField(blank=True, default='placeholder', upload_to='tripDayImages/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='travellerprofile.traveller')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='trips.trip')),
            ],
        ),
    ]
