# Generated by Django 4.2.11 on 2024-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_tripday'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripday',
            name='dayDate',
            field=models.DateField(auto_now=True),
        ),
    ]
