# Generated by Django 4.2.11 on 2024-03-20 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_tripday_daydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripday',
            old_name='trip_photo',
            new_name='day_photo',
        ),
    ]
