# Generated by Django 4.2.11 on 2024-03-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_rename_trip_photo_tripday_day_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripday',
            old_name='dayDate',
            new_name='day_date',
        ),
    ]
