# Generated by Django 4.2.11 on 2024-03-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_rename_daydate_tripday_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripday',
            name='locations',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
