# Generated by Django 4.2.11 on 2024-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_tripday_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='excerpt',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
